import json
from pathlib import Path

path = Path(__file__).resolve().parent.parent / 'assets' / 'data' / 'english_placement_question_bank.json'
passages = {
    'a2_park_notice': 'Welcome to Greenway Park. Please keep the paths clear for cyclists and walkers. Dogs must remain on a short lead. Barbecues are allowed only in the designated area near the lake. Loud music is not permitted after 8 pm. Thank you for helping us keep the park clean and safe for everyone.',
    'b1_volunteer_event': 'Last Saturday, a group of volunteers helped repaint the community centre. Each team worked on a different room, and everyone received a short training session before starting. The coordinator thanked the volunteers for arriving on time and reminded them to wear protective gloves. After the work, the team shared snacks and talked about ideas for the next event.',
    'b1_travel_guide': 'When visiting a new city, it is helpful to carry a small notebook. Write the names of the streets you need, and note the opening hours of places you want to see. Asking local people for directions is polite if you begin with "Excuse me." You should also check the weather forecast before you leave, since rain might change your plans for an outdoor market or a walking tour.',
    'b2_environment_project': 'A youth group decided to start a neighbourhood recycling programme. They met several times to plan the campaign, research local recycling rules and design posters. During a workshop, members discussed how to encourage households to separate paper, plastic and glass. They also invited a guest speaker to explain how recycled materials can become new products. As a result, more residents began using the bins correctly and the organisers prepared a short report for the town council.',
}

def build_question(data):
    data = dict(data)
    data['options'] = [{'text': text} for text in data.get('options', []) if text is not None]
    data['acceptedAnswers'] = data.get('acceptedAnswers', [])
    data['weight'] = data.get('weight', {'A2': 1, 'B1': 2, 'B2': 3}[data['level']])
    if data.get('passageId') and not data.get('passage'):
        data['passage'] = passages[data['passageId']]
    return data

questions = [
    build_question({'id':'eng_a2_001','type':'notice_meaning','level':'A2','skill':'use_of_english','title':'Park Notice','instruction':'Choose the best meaning.','passageId':None,'question':'The sign says: "Keep off the grass." What should visitors do?','options':['Stay on the path','Pick flowers','Play on the grass','Feed the ducks'],'correctOptionIndex':0,'explanation':'Visitors should stay off the grass and use the path.'}),
    build_question({'id':'eng_a2_002','type':'notice_meaning','level':'A2','skill':'communication','title':'Travel Update','instruction':'Choose the main message.','passageId':None,'question':'The schedule note reads: "Lift closed today between 10 am and 2 pm." What does it mean?','options':['Use the stairs at those times','The lift is open after 2 pm','The lift is free today','The lift is moving slowly'],'correctOptionIndex':0,'explanation':'The note warns that the lift is closed during that period.'}),
    build_question({'id':'eng_a2_003','type':'notice_meaning','level':'A2','skill':'communication','title':'Accommodation Rule','instruction':'Choose the correct action.','passageId':None,'question':'The notice says: "Please remove your shoes before entering the lounge." What should guests do?','options':['Take off shoes first','Bring food into the lounge','Sit quietly on the floor','Leave the lounge before noon'],'correctOptionIndex':0,'explanation':'Guests should remove shoes before entering.'}),
    build_question({'id':'eng_a2_004','type':'multiple_choice_cloze','level':'A2','skill':'grammar','title':'Present Simple','instruction':'Choose the correct word.','passageId':None,'question':'She ____ to the bus stop every morning.','options':['walk','walks','walking','walked'],'correctOptionIndex':1,'explanation':'We use walks for she/he/it in the present simple.'}),
    build_question({'id':'eng_a2_005','type':'vocabulary','level':'A2','skill':'vocabulary','title':'Everyday Choice','instruction':'Choose the best word.','passageId':None,'question':'I need a ____ for my homework.','options':['notebook','wallet','umbrella','sandwich'],'correctOptionIndex':0,'explanation':'Notebook is correct for homework writing.'}),
    build_question({'id':'eng_a2_006','type':'open_cloze','level':'A2','skill':'use_of_english','title':'Preposition','instruction':'Complete the sentence.','passageId':None,'question':'I will meet you ____ the café at five.','acceptedAnswers':['at'],'explanation':'Use at with a place and time.'}),
    build_question({'id':'eng_a2_007','type':'word_formation','level':'A2','skill':'vocabulary','title':'Word Building','instruction':'Use the correct form of the word HAPPY.','passageId':None,'question':'The child felt very ____.','acceptedAnswers':['happy'],'explanation':'The adjective form fits the sentence.'}),
    build_question({'id':'eng_a2_008','type':'sentence_transformation','level':'A2','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "because".','passageId':None,'question':'I stayed inside because it was raining.','acceptedAnswers':['I stayed inside because it was raining.'],'sentence':'I stayed inside. It was raining.','keyword':'because','explanation':'The sentence keeps the same meaning using because.'}),
    build_question({'id':'eng_a2_009','type':'reading_comprehension','level':'A2','skill':'reading','title':'Short Passage','instruction':'Choose the correct detail.','passageId':'a2_park_notice','question':'How should visitors behave in the park?','options':['Bring bicycles to ride','Keep the paths clear','Play loud music','Feed the ducks'],'correctOptionIndex':1,'explanation':'The passage asks visitors to keep paths clear.'}),
    build_question({'id':'eng_a2_010','type':'multiple_choice_cloze','level':'A2','skill':'grammar','title':'Simple Past','instruction':'Choose the correct form.','passageId':None,'question':'Yesterday I ____ a letter to my friend.','options':['write','wrote','written','writes'],'correctOptionIndex':1,'explanation':'Wrote is the past simple form.'}),
    build_question({'id':'eng_a2_011','type':'vocabulary','level':'A2','skill':'vocabulary','title':'Time Words','instruction':'Choose the word that fits.','passageId':None,'question':'I am busy now, but I will help you ____.','options':['tomorrow','yesterday','always','never'],'correctOptionIndex':0,'explanation':'Tomorrow refers to a later time.'}),
    build_question({'id':'eng_a2_012','type':'open_cloze','level':'A2','skill':'grammar','title':'Article','instruction':'Complete the sentence.','passageId':None,'question':'She has ____ orange backpack.','acceptedAnswers':['an'],'explanation':'Use an before a vowel sound.'}),
    build_question({'id':'eng_a2_013','type':'word_formation','level':'A2','skill':'vocabulary','title':'Word Form','instruction':'Use the correct form of the word FRIEND.','passageId':None,'question':'He is a good ____.','acceptedAnswers':['friend'],'explanation':'The noun form friend is correct.'}),
    build_question({'id':'eng_a2_014','type':'sentence_transformation','level':'A2','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "too".','passageId':None,'question':'It was too warm, and I felt tired.','acceptedAnswers':['It was too warm, and I felt tired.'],'sentence':'It was very warm, and I felt tired.','keyword':'too','explanation':'The sentence uses too to show excess.'}),
    build_question({'id':'eng_a2_015','type':'multiple_choice_cloze','level':'A2','skill':'grammar','title':'Past Simple','instruction':'Choose the correct answer.','passageId':None,'question':'Last week we ____ at the beach.','options':['are','were','is','was'],'correctOptionIndex':1,'explanation':'Were is used with we in past simple.'}),
    build_question({'id':'eng_a2_016','type':'vocabulary','level':'A2','skill':'vocabulary','title':'Common Object','instruction':'Choose the best answer.','passageId':None,'question':'Please hand me the ____.','options':['bag','moon','ocean','forest'],'correctOptionIndex':0,'explanation':'Bag is the only object you can hand over.'}),
    build_question({'id':'eng_a2_017','type':'open_cloze','level':'A2','skill':'grammar','title':'Pronoun','instruction':'Complete the sentence.','passageId':None,'question':'This is Mark and ____ sister.','acceptedAnswers':['his'],'explanation':'His refers to Mark.'}),
    build_question({'id':'eng_a2_018','type':'word_formation','level':'A2','skill':'vocabulary','title':'Word Formation','instruction':'Use the correct form of the word CLEAN.','passageId':None,'question':'The room looks ____.','acceptedAnswers':['clean'],'explanation':'Clean is the adjective form.'}),
    build_question({'id':'eng_a2_019','type':'sentence_transformation','level':'A2','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "before".','passageId':None,'question':'I watched a movie after I finished dinner.','acceptedAnswers':['I watched a movie after I finished dinner.'],'sentence':'I finished dinner. I watched a movie.','keyword':'before','explanation':'The sentence changes order using before/after.'}),
    build_question({'id':'eng_a2_020','type':'vocabulary','level':'A2','skill':'vocabulary','title':'Everyday Verb','instruction':'Choose the correct word.','passageId':None,'question':'She ____ water every day.','options':['drink','drinks','drinking','drank'],'correctOptionIndex':1,'explanation':'Drinks is correct for she in present simple.'}),
    build_question({'id':'eng_a2_021','type':'multiple_choice_cloze','level':'A2','skill':'use_of_english','title':'Simple Question','instruction':'Choose the correct question.','passageId':None,'question':'____ you like tea?','options':['Do','Does','Did','Are'],'correctOptionIndex':0,'explanation':'Do is used with you in present simple.'}),
    build_question({'id':'eng_a2_022','type':'notice_meaning','level':'A2','skill':'communication','title':'Room Notice','instruction':'Choose the right action.','passageId':None,'question':'The sign says: "Quiet please: study area." What should people do?','options':['Speak softly','Run inside','Leave chairs outside','Eat snacks loudly'],'correctOptionIndex':0,'explanation':'The notice asks for quiet in the study area.'}),
    build_question({'id':'eng_a2_023','type':'open_cloze','level':'A2','skill':'grammar','title':'Conjunction','instruction':'Complete the sentence.','passageId':None,'question':'I want to play, ____ I have homework.','acceptedAnswers':['but'],'explanation':'But shows contrast.'}),
    build_question({'id':'eng_a2_024','type':'word_formation','level':'A2','skill':'vocabulary','title':'Word Form','instruction':'Use the correct form of the word HELP.','passageId':None,'question':'She gave me some ____.','acceptedAnswers':['help'],'explanation':'Help is a noun here.'}),
    build_question({'id':'eng_b1_001','type':'notice_meaning','level':'B1','skill':'communication','title':'Event Notice','instruction':'Choose the main message.','passageId':None,'question':'The note says: "Please arrive at the meeting room by 9:15 so we can start on time." What should attendees do?','options':['Come early enough to be ready','Bring snacks for everyone','Leave before 9:15','Wear a green shirt'],'correctOptionIndex':0,'explanation':'Attendees should arrive by 9:15 to begin on time.'}),
    build_question({'id':'eng_b1_002','type':'multiple_choice_cloze','level':'B1','skill':'grammar','title':'Present Perfect','instruction':'Choose the best answer.','passageId':None,'question':'I ____ this book three times already.','options':['read','have read','was reading','will read'],'correctOptionIndex':1,'explanation':'Present perfect uses have/has + past participle.'}),
    build_question({'id':'eng_b1_003','type':'multiple_choice_cloze','level':'B1','skill':'grammar','title':'Modal Verbs','instruction':'Choose the best answer.','passageId':None,'question':'You ____ take your umbrella; it might rain later.','options':['must','should','can','will'],'correctOptionIndex':1,'explanation':'Should suggests advice about rain.'}),
    build_question({'id':'eng_b1_004','type':'multiple_choice_cloze','level':'B1','skill':'use_of_english','title':'Conditionals','instruction':'Choose the correct sentence.','passageId':None,'question':'If I ____ more time, I would join the class.','options':['have','had','will have','would have'],'correctOptionIndex':1,'explanation':'Second conditional uses had.'}),
    build_question({'id':'eng_b1_005','type':'vocabulary','level':'B1','skill':'vocabulary','title':'Collocation','instruction':'Choose the best phrase.','passageId':None,'question':'The team made a ____ decision before the event.','options':['fast','quick','swift','speedy'],'correctOptionIndex':1,'explanation':'Quick collocates naturally with decision.'}),
    build_question({'id':'eng_b1_006','type':'open_cloze','level':'B1','skill':'grammar','title':'Prepositions','instruction':'Complete the sentence.','passageId':None,'question':'She has been working here ____ January.','acceptedAnswers':['since'],'explanation':'Since introduces the starting point.'}),
    build_question({'id':'eng_b1_007','type':'word_formation','level':'B1','skill':'vocabulary','title':'Word Formation','instruction':'Use the correct form of the word ENJOY.','passageId':None,'question':'They had great ____.','acceptedAnswers':['enjoyment'],'explanation':'Enjoyment is the noun form.'}),
    build_question({'id':'eng_b1_008','type':'sentence_transformation','level':'B1','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "although".','passageId':None,'question':'Although it was cold, we still enjoyed the trip.','acceptedAnswers':['Although it was cold, we still enjoyed the trip.'],'sentence':'It was cold. We still enjoyed the trip.','keyword':'although','explanation':'The sentence keeps the same meaning with although.'}),
    build_question({'id':'eng_b1_009','type':'reading_comprehension','level':'B1','skill':'reading','title':'Volunteer Summary','instruction':'Choose the main idea.','passageId':'b1_volunteer_event','question':'What is the passage mainly about?','options':['How volunteers prepared the community centre','The exact number of people who painted','The weather during the event','The snacks served after work'],'correctOptionIndex':0,'explanation':'The passage focuses on volunteer preparation and teamwork.'}),
    build_question({'id':'eng_b1_010','type':'reading_comprehension','level':'B1','skill':'reading','title':'Volunteer Detail','instruction':'Choose the correct detail.','passageId':'b1_volunteer_event','question':'What did the coordinator remind the volunteers to do?','options':['Bring snacks','Wear protective gloves','Paint only the ceiling','Invite a guest speaker'],'correctOptionIndex':1,'explanation':'The coordinator reminded them to wear gloves.'}),
    build_question({'id':'eng_b1_011','type':'vocabulary','level':'B1','skill':'vocabulary','title':'Phrasal Verb','instruction':'Choose the correct phrasal verb.','passageId':None,'question':'Please ____ the lights when you leave the room.','options':['turn on','turn off','look after','give up'],'correctOptionIndex':1,'explanation':'Turn off matches leaving the room.'}),
    build_question({'id':'eng_b1_012','type':'multiple_choice_cloze','level':'B1','skill':'grammar','title':'Relative Clauses','instruction':'Choose the correct answer.','passageId':None,'question':'The student ____ spoke to me is from Spain.','options':['which','who','where','whose'],'correctOptionIndex':1,'explanation':'Who is used for people.'}),
    build_question({'id':'eng_b1_013','type':'multiple_choice_cloze','level':'B1','skill':'grammar','title':'Past Simple vs Present Perfect','instruction':'Choose the correct sentence.','passageId':None,'question':'I ____ to that museum before.','options':['have been','went','go','will go'],'correctOptionIndex':0,'explanation':'Present perfect indicates experience.'}),
    build_question({'id':'eng_b1_014','type':'open_cloze','level':'B1','skill':'grammar','title':'Conjunctions','instruction':'Complete the sentence.','passageId':None,'question':'He did his homework ____ he watched a video.','acceptedAnswers':['before'],'explanation':'Before shows the order of actions.'}),
    build_question({'id':'eng_b1_015','type':'word_formation','level':'B1','skill':'vocabulary','title':'Word Formation','instruction':'Use the correct form of the word ACTIVE.','passageId':None,'question':'Her ____ helps the team move quickly.','acceptedAnswers':['activity'],'explanation':'Activity is the noun form.'}),
    build_question({'id':'eng_b1_016','type':'sentence_transformation','level':'B1','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "unless".','passageId':None,'question':'I will go unless it rains.','acceptedAnswers':['I will go unless it rains.'],'sentence':'I will go only if it does not rain.','keyword':'unless','explanation':'The sentence maintains meaning with unless.'}),
    build_question({'id':'eng_b1_017','type':'reading_comprehension','level':'B1','skill':'reading','title':'Guide Detail','instruction':'Choose the correct detail.','passageId':'b1_travel_guide','question':'What should you write in a notebook?','options':['The names of streets','Your favourite song','A recipe for dinner','A list of books'],'correctOptionIndex':0,'explanation':'Write street names.'}),
    build_question({'id':'eng_b1_018','type':'reading_comprehension','level':'B1','skill':'reading','title':'Guide Inference','instruction':'Choose the best inference.','passageId':'b1_travel_guide','question':'Why is it polite to say “Excuse me”?','options':['To begin a polite question','To cancel plans','To report a problem','To buy a ticket'],'correctOptionIndex':0,'explanation':'It is polite when asking for directions.'}),
    build_question({'id':'eng_b1_019','type':'gapped_text','level':'B1','skill':'reading','title':'Text Cohesion','instruction':'Choose the sentence that fits the text.','passageId':'b1_travel_guide','question':'A small notebook helps you remember street names and opening hours. ____, you can ask politely if you need help.','options':['Therefore','While','However','Since'],'correctOptionIndex':3,'explanation':'Since explains the reason to check the weather.'}),
    build_question({'id':'eng_b1_020','type':'situational_communication','level':'B1','skill':'communication','title':'Practical Response','instruction':'Choose the best reply.','passageId':None,'question':'A coordinator says: "Could you confirm the arrival time?" What is the polite answer?','options':['Yes, I will arrive at 9.','Maybe I will come later.','No, I won’t tell you.','I do not know anything.'],'correctOptionIndex':0,'explanation':'The polite reply confirms the arrival time.'}),
    build_question({'id':'eng_b1_021','type':'multiple_choice_cloze','level':'B1','skill':'grammar','title':'Modal Deduction','instruction':'Choose the correct answer.','passageId':None,'question':'She is not at home, so she ____ at work.','options':['must be','can be','might to be','should has been'],'correctOptionIndex':0,'explanation':'Must be shows strong certainty.'}),
    build_question({'id':'eng_b1_022','type':'vocabulary','level':'B1','skill':'vocabulary','title':'Common Expression','instruction':'Choose the best meaning.','passageId':None,'question':'The meeting was called off. What does this mean?','options':['It was canceled','It started early','It changed location','It became louder'],'correctOptionIndex':0,'explanation':'Called off means canceled.'}),
    build_question({'id':'eng_b1_023','type':'open_cloze','level':'B1','skill':'grammar','title':'Auxiliary Verb','instruction':'Complete the sentence.','passageId':None,'question':'____ you ever been to a youth conference?','acceptedAnswers':['Have'],'explanation':'Have is the auxiliary for present perfect questions.'}),
    build_question({'id':'eng_b1_024','type':'word_formation','level':'B1','skill':'vocabulary','title':'Word Formation','instruction':'Use the correct form of the word INVITE.','passageId':None,'question':'The hosts sent an official ____.','acceptedAnswers':['invitation'],'explanation':'Invitation is the noun form.'}),
    build_question({'id':'eng_b1_025','type':'sentence_transformation','level':'B1','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "still".','passageId':None,'question':'She still has not finished.','acceptedAnswers':['She still has not finished.'],'sentence':'She has not finished, and she continues working.','keyword':'still','explanation':'Still keeps the same meaning.'}),
    build_question({'id':'eng_b1_026','type':'multiple_choice_cloze','level':'B1','skill':'grammar','title':'Second Conditional','instruction':'Choose the correct form.','passageId':None,'question':'If I had more money, I ____ buy the course.','options':['will','would','can','must'],'correctOptionIndex':1,'explanation':'Would is used in second conditionals.'}),
    build_question({'id':'eng_b1_027','type':'vocabulary','level':'B1','skill':'vocabulary','title':'Phrase Choice','instruction':'Choose the best word.','passageId':None,'question':'He is good at ____ people with clear instructions.','options':['explaining','explain','explained','explains'],'correctOptionIndex':0,'explanation':'Explaining is the correct gerund form.'}),
    build_question({'id':'eng_b1_028','type':'open_cloze','level':'B1','skill':'grammar','title':'Pronouns','instruction':'Complete the sentence.','passageId':None,'question':'Everyone brought ____ own passport.','acceptedAnswers':['their'],'explanation':'Their is used for singular they.'}),
    build_question({'id':'eng_b1_029','type':'word_formation','level':'B1','skill':'vocabulary','title':'Word Formation','instruction':'Use the correct form of the word CREATE.','passageId':None,'question':'The team shared their ____.','acceptedAnswers':['creations'],'explanation':'Creations is the noun form.'}),
    build_question({'id':'eng_b1_030','type':'sentence_transformation','level':'B1','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "unless".','passageId':None,'question':'I will go unless I am too tired.','acceptedAnswers':['I will go unless I am too tired.'],'sentence':'I will not go because I am tired.','keyword':'unless','explanation':'The sentence keeps the same meaning.'}),
    build_question({'id':'eng_b1_031','type':'multiple_choice_cloze','level':'B1','skill':'grammar','title':'Future with Will','instruction':'Choose the correct option.','passageId':None,'question':'I think I ____ finish the report by tomorrow.','options':['will','would','should','must'],'correctOptionIndex':0,'explanation':'Will is used for a simple future prediction.'}),
    build_question({'id':'eng_b1_032','type':'vocabulary','level':'B1','skill':'vocabulary','title':'Daily Routine','instruction':'Choose the correct word.','passageId':None,'question':'She always ____ her teeth after breakfast.','options':['brushes','brushed','brushing','brush'],'correctOptionIndex':0,'explanation':'Brushes is the correct present simple form for she.'}),
    build_question({'id':'eng_b1_033','type':'open_cloze','level':'B1','skill':'grammar','title':'Comparative','instruction':'Complete the sentence.','passageId':None,'question':'This book is ____ than the last one.','acceptedAnswers':['better'],'explanation':'Better is the comparative form of good.'}),
    build_question({'id':'eng_b1_034','type':'sentence_transformation','level':'B1','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "because".','passageId':None,'question':'She could not come to the meeting because she was ill.','acceptedAnswers':['She could not come to the meeting because she was ill.'],'sentence':'She was ill. She could not come to the meeting.','keyword':'because','explanation':'The sentence keeps the same meaning with because.'}),
    build_question({'id':'eng_b1_035','type':'reading_comprehension','level':'B1','skill':'reading','title':'Simple Notice','instruction':'Choose the correct detail.','passageId':None,'question':'A notice says: "The library is closed on Sunday." What does it mean?','options':['The library is not open on Sunday','The library opens on Sunday','Sunday is discount day','The library closes early daily'],'correctOptionIndex':0,'explanation':'The notice means the library is closed on Sunday.'}),
    build_question({'id':'eng_b1_036','type':'situational_communication','level':'B1','skill':'communication','title':'Polite Request','instruction':'Choose the best reply.','passageId':None,'question':'Someone asks: "Could you hand me the folder, please?" What is the best answer?','options':['Sure, here it is.','No, I will not.','Maybe later.','I cannot see it.'],'correctOptionIndex':0,'explanation':'A polite request is answered with a helpful reply.'}),
    build_question({'id':'eng_b2_001','type':'multiple_choice_cloze','level':'B2','skill':'grammar','title':'Mixed Conditionals','instruction':'Choose the correct sentence.','passageId':None,'question':'If she had studied law, she ____ be a lawyer now.','options':['would','would have','will','would be'],'correctOptionIndex':3,'explanation':'A mixed conditional uses would be for present result.'}),
    build_question({'id':'eng_b2_002','type':'multiple_choice_cloze','level':'B2','skill':'grammar','title':'Reported Speech','instruction':'Choose the correct reported form.','passageId':None,'question':'Direct: "I am leaving now," she said. Reported: She said that she ____.','options':['was leaving','is leaving','left','would leave'],'correctOptionIndex':0,'explanation':'Was leaving is the correct past reporting form.'}),
    build_question({'id':'eng_b2_003','type':'vocabulary','level':'B2','skill':'vocabulary','title':'Collocation','instruction':'Choose the best phrase.','passageId':None,'question':'The speaker gave a ____ overview of the programme.','options':['clear','clarified','clarity','clearer'],'correctOptionIndex':0,'explanation':'Clear overview is the natural phrase.'}),
    build_question({'id':'eng_b2_004','type':'open_cloze','level':'B2','skill':'grammar','title':'Linking Words','instruction':'Complete the sentence.','passageId':None,'question':'They chose to postpone the activity ____ the weather forecast.','acceptedAnswers':['because of'],'explanation':'Because of explains the reason.'}),
    build_question({'id':'eng_b2_005','type':'word_formation','level':'B2','skill':'vocabulary','title':'Word Formation','instruction':'Use the correct form of the word PARTICIPATE.','passageId':None,'question':'Widespread ____. increased the project’s visibility.','acceptedAnswers':['participation'],'explanation':'Participation is the noun.'}),
    build_question({'id':'eng_b2_006','type':'sentence_transformation','level':'B2','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "unless".','passageId':None,'question':'I will send the report unless it is incomplete.','acceptedAnswers':['I will send the report unless it is incomplete.'],'sentence':'I will not send the report if it is incomplete.','keyword':'unless','explanation':'Maintains meaning.'}),
    build_question({'id':'eng_b2_007','type':'reading_comprehension','level':'B2','skill':'reading','title':'Program Description','instruction':'Choose the writer’s attitude.','passageId':'b2_environment_project','question':'What is the writer’s attitude toward the recycling programme?','options':['Positive and hopeful','Critical and angry','Neutral and bored','Confused and doubtful'],'correctOptionIndex':0,'explanation':'The writer is positive about the programme.'}),
    build_question({'id':'eng_b2_008','type':'reading_comprehension','level':'B2','skill':'reading','title':'Program Detail','instruction':'Choose the correct detail.','passageId':'b2_environment_project','question':'What did the youth group do during the workshop?','options':['Discussed how to encourage households','Painted the community centre','Visited the town council','Designed a new park'],'correctOptionIndex':0,'explanation':'They discussed encouraging households.'}),
    build_question({'id':'eng_b2_009','type':'gapped_text','level':'B2','skill':'reading','title':'Text Cohesion','instruction':'Choose the sentence that completes the paragraph.','passageId':'b2_environment_project','question':'A youth group planned a campaign and designed posters. ____, more residents began using the bins correctly.','options':['As a result','In contrast','Meanwhile','At first'],'correctOptionIndex':0,'explanation':'As a result shows the effect of the speaker.'}),
    build_question({'id':'eng_b2_010','type':'situational_communication','level':'B2','skill':'communication','title':'Coordinator Email','instruction':'Choose the best response.','passageId':None,'question':'A coordinator writes: "Please confirm whether you can attend the training session." What is the best reply?','options':['Yes, I can attend the training session.','I am not sure.','Maybe I will think about it.','I do not want to attend.'],'correctOptionIndex':0,'explanation':'A clear confirmation is best.'}),
    build_question({'id':'eng_b2_011','type':'multiple_choice_cloze','level':'B2','skill':'grammar','title':'Advanced Tense','instruction':'Choose the correct form.','passageId':None,'question':'By the time she arrives, we ____ the plans.','options':['will finish','will have finished','have finished','finished'],'correctOptionIndex':1,'explanation':'Future perfect is used for an action completed before another future action.'}),
    build_question({'id':'eng_b2_012','type':'vocabulary','level':'B2','skill':'vocabulary','title':'Register','instruction':'Choose the most formal word.','passageId':None,'question':'The committee issued a formal ____.','options':['announcement','talk','chat','message'],'correctOptionIndex':0,'explanation':'Announcement is formal and appropriate.'}),
    build_question({'id':'eng_b2_013','type':'open_cloze','level':'B2','skill':'grammar','title':'Passive Voice','instruction':'Complete the sentence.','passageId':None,'question':'The report ____ by the team before the meeting.','acceptedAnswers':['was prepared'],'explanation':'Was prepared is passive past form.'}),
    build_question({'id':'eng_b2_014','type':'word_formation','level':'B2','skill':'vocabulary','title':'Word Formation','instruction':'Use the correct form of the word ORGANISE.','passageId':None,'question':'The campaign was ____.','acceptedAnswers':['organised'],'explanation':'Organised is the adjective form.'}),
    build_question({'id':'eng_b2_015','type':'sentence_transformation','level':'B2','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "despite".','passageId':None,'question':'Despite the rain, they continued the activity.','acceptedAnswers':['Despite the rain, they continued the activity.'],'sentence':'It rained, but they continued the activity.','keyword':'despite','explanation':'Same meaning with despite.'}),
    build_question({'id':'eng_b2_016','type':'reading_comprehension','level':'B2','skill':'reading','title':'Program Inference','instruction':'Choose the best inference.','passageId':'b2_environment_project','question':'What can you infer about the town council?','options':['They welcomed the recycling report','They rejected the plan immediately','They were unaware of the project','They disliked the youth group'],'correctOptionIndex':0,'explanation':'The town council likely welcomed the report.'}),
    build_question({'id':'eng_b2_017','type':'multiple_choice_cloze','level':'B2','skill':'grammar','title':'Modal Deduction','instruction':'Choose the correct answer.','passageId':None,'question':'He ____ have missed the bus because he is not here yet.','options':['must','might','can','should'],'correctOptionIndex':0,'explanation':'Must have expresses a strong deduction.'}),
    build_question({'id':'eng_b2_018','type':'vocabulary','level':'B2','skill':'vocabulary','title':'Word Choice','instruction':'Choose the best word.','passageId':None,'question':'The project gained wide ____.','options':['attention','attentive','attend','attaining'],'correctOptionIndex':0,'explanation':'Attention is the correct noun.'}),
    build_question({'id':'eng_b2_019','type':'open_cloze','level':'B2','skill':'grammar','title':'Conditionals','instruction':'Complete the sentence.','passageId':None,'question':'If they had known the rules, they ____ the task differently.','acceptedAnswers':['would have done'],'explanation':'Would have done is third conditional.'}),
    build_question({'id':'eng_b2_020','type':'word_formation','level':'B2','skill':'vocabulary','title':'Word Formation','instruction':'Use the correct form of the word CREATE.','passageId':None,'question':'The event was highly ____.','acceptedAnswers':['creative'],'explanation':'Creative is the adjective form.'}),
    build_question({'id':'eng_b2_021','type':'sentence_transformation','level':'B2','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "so".','passageId':None,'question':'The team worked hard so they could help.','acceptedAnswers':['The team worked hard so they could help.'],'sentence':'The team worked hard because they wanted to help.','keyword':'so','explanation':'Keeps the cause and effect.'}),
    build_question({'id':'eng_b2_022','type':'situational_communication','level':'B2','skill':'communication','title':'Request Clarification','instruction':'Choose the best reply.','passageId':None,'question':'A mentor says: "Please tell me more about your availability." What should you answer?','options':['I am available on weekdays after 5 pm.','I do not know when.','I might be free.','Yes.'],'correctOptionIndex':0,'explanation':'A clear answer about availability is best.'}),
    build_question({'id':'eng_b2_023','type':'multiple_choice_cloze','level':'B2','skill':'grammar','title':'Advanced Collocation','instruction':'Choose the correct phrase.','passageId':None,'question':'They need to ____ the project timeline carefully.','options':['review','reviewed','reviewing','reviews'],'correctOptionIndex':0,'explanation':'Review the timeline is the correct phrase.'}),
    build_question({'id':'eng_b2_024','type':'vocabulary','level':'B2','skill':'vocabulary','title':'Register and Tone','instruction':'Choose the most appropriate expression.','passageId':None,'question':'Please let me know if you require further information. What does this phrase show?','options':['Politeness','Anger','Confusion','Urgency'],'correctOptionIndex':0,'explanation':'The phrase expresses politeness.'}),
    build_question({'id':'eng_b2_025','type':'open_cloze','level':'B2','skill':'grammar','title':'Relative Words','instruction':'Complete the sentence.','passageId':None,'question':'The student ____ work was excellent received praise.','acceptedAnswers':['whose'],'explanation':'Whose introduces possession.'}),
    build_question({'id':'eng_b2_026','type':'word_formation','level':'B2','skill':'vocabulary','title':'Word Formation','instruction':'Use the correct form of the word SUSTAIN.','passageId':None,'question':'The programme showed ____.','acceptedAnswers':['sustainability'],'explanation':'Sustainability is the noun form.'}),
    build_question({'id':'eng_b2_027','type':'sentence_transformation','level':'B2','skill':'grammar','title':'Same Meaning','instruction':'Rewrite with the word "although".','passageId':None,'question':'Although they were tired, they finished the task.','acceptedAnswers':['Although they were tired, they finished the task.'],'sentence':'They were tired. They finished the task.','keyword':'although','explanation':'Keeps the same meaning.'}),
    build_question({'id':'eng_b2_028','type':'reading_comprehension','level':'B2','skill':'reading','title':'Organization','instruction':'Choose the correct structure.','passageId':'b2_environment_project','question':'What is the main organizational feature of the passage?','options':['It describes planning, action, and result.','It compares two unrelated projects.','It lists equipment only.','It explains a personal story.'],'correctOptionIndex':0,'explanation':'The passage is organized around planning, action, and result.'}),
    build_question({'id':'eng_b2_029','type':'gapped_text','level':'B2','skill':'reading','title':'Text Link','instruction':'Choose the sentence that improves cohesion.','passageId':'b2_environment_project','question':'The youth group planned a campaign and designed posters. ____, many households started recycling properly.','options':['Therefore','Meanwhile','Afterwards','Above all'],'correctOptionIndex':0,'explanation':'Therefore links the plan to the result.'}),
    build_question({'id':'eng_b2_030','type':'situational_communication','level':'B2','skill':'communication','title':'Request Information','instruction':'Choose the best reply.','passageId':None,'question':'A volunteer coordinator asks: "What is your preferred role in the project?" What is the best answer?','options':['I prefer to support logistics and communication.','I do not care.','Maybe I can help later.','I only want to watch.'],'correctOptionIndex':0,'explanation':'A clear, helpful answer is best.'}),
]

with path.open('w', encoding='utf-8') as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print('Written', len(questions), 'questions to', path)
